/// Registration entry for TypeScript type generation.
///
/// Each entity annotated with `#[derive(SyncEntity)]` registers a
/// `TsTypeRegistration` via the [`inventory`] crate. At codegen time,
/// [`generate_ts_file`] collects all registrations and emits a complete
/// TypeScript module with:
///
/// - Branded `Id<Tag>` type for type-safe entity IDs
/// - `{Entity}Full` and `{Entity}Patch` interfaces matching the Rust structs
/// - `EntityTag` union type
/// - `InboundMessage` discriminated union (server-to-client)
/// - `OutboundCommand` and `OutboundHandshake` interfaces (client-to-server)
///
/// # Registration (automatic)
///
/// The `SyncEntity` derive macro generates registrations automatically:
///
/// ```text
/// inventory::submit! {
///     TsTypeRegistration {
///         entity_name: "Order",
///         ts_full_interface: "export interface OrderFull { ... }",
///         ts_patch_interface: "export interface OrderPatch { ... }",
///     }
/// }
/// ```
///
/// # Type mappings
///
/// | Rust type             | TypeScript type           |
/// |-----------------------|---------------------------|
/// | `String`              | `string`                  |
/// | `bool`                | `boolean`                 |
/// | `i32`, `u64`, etc.    | `number`                  |
/// | `Decimal`             | `string`                  |
/// | `Id<Tag>`             | `Id<"Tag">`               |
/// | `BTreeMap<K, V>`      | `Record<K, V>`            |
/// | `Option<T>`           | `T \| null`               |
pub struct TsTypeRegistration {
    pub entity_name: &'static str,
    pub ts_full_interface: &'static str,
    pub ts_patch_interface: &'static str,
}

inventory::collect!(TsTypeRegistration);

/// Collect all registered TypeScript type definitions and produce the full
/// `sync.ts` file content.
///
/// This function iterates over all [`TsTypeRegistration`] entries submitted
/// via `inventory` and assembles them into a single TypeScript module. The
/// output includes:
///
/// 1. **`Id<Tag>` branded type** -- A nominal type wrapper for UUID strings,
///    preventing accidental mixing of entity IDs in TypeScript.
/// 2. **Entity interfaces** -- `{Name}Full` and `{Name}Patch` for each
///    registered entity, sorted alphabetically by entity name.
/// 3. **`EntityTag` union** -- A string literal union of all entity names.
/// 4. **`InboundMessage` discriminated union** -- Server-to-client messages,
///    discriminated on `entityTag` + `kind`.
/// 5. **`OutboundCommand` / `OutboundHandshake`** -- Client-to-server types.
///
/// The generated file is prefixed with `// AUTO-GENERATED — DO NOT EDIT`.
///
/// # Usage
///
/// Typically called from a `bin/codegen.rs` binary:
///
/// ```text
/// fn main() {
///     domain::register_entities();
///     let content = sync_core::ts::generate_ts_file();
///     std::fs::write("packages/client/generated/sync.ts", content).unwrap();
/// }
/// ```
pub fn generate_ts_file() -> String {
    let mut output = String::new();

    // Header
    output.push_str("// AUTO-GENERATED — DO NOT EDIT\n");
    output.push_str("// Generated by build.rs from Rust SyncEntity definitions\n\n");

    // Id branded type
    output.push_str("/** Branded UUID type for type-safe entity IDs */\n");
    output.push_str("export type Id<Tag extends string> = { readonly _tag: Tag; readonly value: string };\n\n");
    output.push_str("export function makeId<Tag extends string>(value: string): Id<Tag> {\n");
    output.push_str("  return { _tag: undefined as unknown as Tag, value } as Id<Tag>;\n");
    output.push_str("}\n\n");

    // Collect all registrations
    let mut registrations: Vec<&TsTypeRegistration> = inventory::iter::<TsTypeRegistration>().collect();
    registrations.sort_by_key(|r| r.entity_name);

    let mut entity_tags = Vec::new();

    for reg in &registrations {
        output.push_str(reg.ts_full_interface);
        output.push('\n');
        output.push_str(reg.ts_patch_interface);
        output.push('\n');
        entity_tags.push(reg.entity_name);
    }

    // EntityTag union
    if !entity_tags.is_empty() {
        output.push_str("export type EntityTag = ");
        let tags: Vec<String> = entity_tags.iter().map(|t| format!("\"{}\"", t)).collect();
        output.push_str(&tags.join(" | "));
        output.push_str(";\n\n");
    }

    // Message kind
    output.push_str("export type MessageKind = \"full\" | \"patch\";\n\n");

    // Inbound message (server → client) discriminated union
    output.push_str("export type InboundMessage =\n");
    for (i, reg) in registrations.iter().enumerate() {
        let name = reg.entity_name;
        output.push_str(&format!(
            "  | {{ entityTag: \"{name}\"; entityId: Id<\"{name}\">; kind: \"full\"; payload: {name}Full }}\n"
        ));
        output.push_str(&format!(
            "  | {{ entityTag: \"{name}\"; entityId: Id<\"{name}\">; kind: \"patch\"; payload: {name}Patch }}\n"
        ));
        if i < registrations.len() - 1 {
            // more entries
        }
    }
    output.push_str(";\n\n");

    // Outbound command
    output.push_str("export interface OutboundCommand {\n");
    output.push_str("  requestId: string;\n");
    output.push_str("  command: string;\n");
    output.push_str("  payload: Record<string, unknown>;\n");
    output.push_str("}\n\n");

    // Outbound handshake
    output.push_str("export interface OutboundHandshake {\n");
    output.push_str("  entityTag: EntityTag;\n");
    output.push_str("  entityId: string;\n");
    output.push_str("  kind: \"patch\";\n");
    output.push_str("  payload: Record<string, unknown>;\n");
    output.push_str("}\n\n");

    output.push_str("export type OutboundMessage = OutboundCommand | OutboundHandshake;\n");

    output
}
