/// Registration entry for TypeScript type generation.
/// Each SyncEntity registers its TS interfaces via `inventory`.
pub struct TsTypeRegistration {
    pub entity_name: &'static str,
    pub ts_full_interface: &'static str,
    pub ts_patch_interface: &'static str,
}

inventory::collect!(TsTypeRegistration);

/// Collect all registered TypeScript type definitions and produce the full
/// `sync.ts` file content.
pub fn generate_ts_file() -> String {
    let mut output = String::new();

    // Header
    output.push_str("// AUTO-GENERATED — DO NOT EDIT\n");
    output.push_str("// Generated by build.rs from Rust SyncEntity definitions\n\n");

    // Id branded type
    output.push_str("/** Branded UUID type for type-safe entity IDs */\n");
    output.push_str("export type Id<Tag extends string> = { readonly _tag: Tag; readonly value: string };\n\n");
    output.push_str("export function makeId<Tag extends string>(value: string): Id<Tag> {\n");
    output.push_str("  return { _tag: undefined as unknown as Tag, value } as Id<Tag>;\n");
    output.push_str("}\n\n");

    // Collect all registrations
    let mut registrations: Vec<&TsTypeRegistration> = inventory::iter::<TsTypeRegistration>().collect();
    registrations.sort_by_key(|r| r.entity_name);

    let mut entity_tags = Vec::new();

    for reg in &registrations {
        output.push_str(reg.ts_full_interface);
        output.push('\n');
        output.push_str(reg.ts_patch_interface);
        output.push('\n');
        entity_tags.push(reg.entity_name);
    }

    // EntityTag union
    if !entity_tags.is_empty() {
        output.push_str("export type EntityTag = ");
        let tags: Vec<String> = entity_tags.iter().map(|t| format!("\"{}\"", t)).collect();
        output.push_str(&tags.join(" | "));
        output.push_str(";\n\n");
    }

    // Message kind
    output.push_str("export type MessageKind = \"full\" | \"patch\";\n\n");

    // Inbound message (server → client) discriminated union
    output.push_str("export type InboundMessage =\n");
    for (i, reg) in registrations.iter().enumerate() {
        let name = reg.entity_name;
        output.push_str(&format!(
            "  | {{ entityTag: \"{name}\"; entityId: Id<\"{name}\">; kind: \"full\"; payload: {name}Full }}\n"
        ));
        output.push_str(&format!(
            "  | {{ entityTag: \"{name}\"; entityId: Id<\"{name}\">; kind: \"patch\"; payload: {name}Patch }}\n"
        ));
        if i < registrations.len() - 1 {
            // more entries
        }
    }
    output.push_str(";\n\n");

    // Outbound command
    output.push_str("export interface OutboundCommand {\n");
    output.push_str("  requestId: string;\n");
    output.push_str("  command: string;\n");
    output.push_str("  payload: Record<string, unknown>;\n");
    output.push_str("}\n\n");

    // Outbound handshake
    output.push_str("export interface OutboundHandshake {\n");
    output.push_str("  entityTag: EntityTag;\n");
    output.push_str("  entityId: string;\n");
    output.push_str("  kind: \"patch\";\n");
    output.push_str("  payload: Record<string, unknown>;\n");
    output.push_str("}\n\n");

    output.push_str("export type OutboundMessage = OutboundCommand | OutboundHandshake;\n");

    output
}
